### ISSUE TITLE
Incompatible matrix shape/size of weights file

### ISSUE THREAD

**Issue by doanthuyennt** [VinAIResearch/dict-guided#1]
Bad predictions due to incompatible matrix shape/size from .yml and .pth files.
![image](https://user-images.githubusercontent.com/43228537/122496676-59d63300-d016-11eb-88c3-85ea52344acf.png)

**Comment by nguyennm1024** [comment]
@doanthuyennt I have updated a new checkpoint to fix this bug. You can download the new pre-trained model and try again
